In [ ]:
from google.colab import files


uploaded = files.upload()

Saving dredger.csv to dredger.csv


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("dredger.csv")

In [ ]:
df

sno  type of land  type of dredger  fuel_consumed(lt/hr)  total_power(kW)  \
0     1             0                1                    31              134   
1     2             1                2                    40              171   
2     3             2                2                    41              176   
3     4             3                0                    34              147   
4     5             1                2                    42              179   
..  ...           ...              ...                   ...              ...   
59   60             2                0                   356             1524   
60   61             3                1                   369             1580   
61   62             2                1                   382             1638   
62   63             1                2                   396             1697   
63   64             0                2                   410             1758   

    volume(m3/hr)  total working hours  Required Pump Power  \
0             700                  800                107.0   
1             600                  600                147.0   
2             800                  900                145.0   
3             900                  560                112.0   
4            1000                  346                140.0   
..            ...                  ...                  ...   
59           6600                  657               1315.0   
60           6700                  456               1368.0   
61           6800                  768               1424.0   
62           6900                  678               1480.0   
63           7000                  576                  NaN   

    Required Cutter Power  
0                    28.0  
1                    24.0  
2                    32.0  
3                    36.0  
4                    40.0  
..                    ...  
59                  266.0  
60                  270.0  
61                  274.0  
62                  278.0  
63                    NaN  

[64 rows x 9 columns]

In [ ]:
df.shape

(64, 9)

In [ ]:
df.describe()

sno  type of land  type of dredger  fuel_consumed(lt/hr)  \
count  64.000000     64.000000        64.000000             64.000000   
mean   32.500000      1.468750         1.031250            158.578125   
std    18.618987      1.112251         0.815889            105.550229   
min     1.000000      0.000000         0.000000             31.000000   
25%    16.750000      0.750000         0.000000             77.500000   
50%    32.500000      1.000000         1.000000            118.000000   
75%    48.250000      2.000000         2.000000            227.250000   
max    64.000000      3.000000         2.000000            410.000000   

       total_power(kW)  volume(m3/hr)  total working hours  \
count        64.000000      64.000000            64.000000   
mean        678.578125    3810.937500           706.171875   
std         452.736786    1903.640388           145.246977   
min         134.000000     600.000000           346.000000   
25%         331.500000    2175.000000           600.000000   
50%         504.000000    3850.000000           690.000000   
75%         971.750000    5425.000000           785.250000   
max        1758.000000    7000.000000           987.000000   

       Required Pump Power  Required Cutter Power  
count            63.000000              63.000000  
mean            531.015873             151.095238  
std             384.245532              76.177152  
min             107.000000              24.000000  
25%             243.500000              85.000000  
50%             361.000000             155.000000  
75%             765.500000             216.000000  
max            1480.000000             278.000000

In [ ]:
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')

In [ ]:
X = df.iloc[:,[1,2,5,6]]
Y = df.iloc[:,[3,4]]

In [ ]:
from sklearn.preprocessing import StandardScaler


In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit(X)

StandardScaler()

In [ ]:

standardized_data = scaler.transform(X)

In [ ]:
print(standardized_data)

[[-1.33095886 -0.03860457 -1.64712321  0.65109693]
 [-0.4247741   1.19674173 -1.70006941 -0.73675331]
 [ 0.48141065  1.19674173 -1.59417701  1.34502205]
 [ 1.38759541 -1.27395087 -1.54123081 -1.01432336]
 [-0.4247741   1.19674173 -1.48828461 -2.49932312]
 [ 0.48141065 -0.03860457 -1.43533841  0.57476517]
 [ 1.38759541 -0.03860457 -1.38239221 -0.9657486 ]
 [-1.33095886 -1.27395087 -1.32944601 -0.21630947]
 [ 0.48141065 -0.03860457 -1.27649981  1.94873691]
 [ 1.38759541  1.19674173 -1.22355361 -0.34121599]
 [-1.33095886 -1.27395087 -1.17060741 -2.12460356]
 [-0.4247741   1.19674173 -1.11766121 -1.43067844]
 [ 1.38759541 -0.03860457 -1.06471501 -0.73675331]
 [ 0.48141065 -1.27395087 -1.01176881 -0.19549172]
 [-1.33095886 -0.03860457 -0.9588226  -0.36203375]
 [-0.4247741  -1.27395087 -0.9058764   0.54700816]
 [ 0.48141065  1.19674173 -0.8529302   0.65109693]
 [-1.33095886 -1.27395087 -0.799984   -0.25100573]
 [-0.4247741  -0.03860457 -0.7470378   1.90016215]
 [ 1.38759541  1.19674173 -0.69

In [ ]:
X = standardized_data
Y = df['fuel_consumed(lt/hr)']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state=2)


In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
model.fit(X_train,Y_train)

LinearRegression()

In [ ]:
y_pred=model.predict(X_test)
y_pred

array([[ 1.85467942e+02,  7.93909337e+02],
       [-1.05579090e+01, -4.57717704e+01],
       [ 2.62668682e+02,  1.12616413e+03],
       [ 3.04436957e+02,  1.30358978e+03],
       [ 1.22257827e+02,  5.20859240e+02],
       [ 2.49030491e+02,  1.06790122e+03],
       [ 1.73892968e+02,  7.44006135e+02],
       [ 1.32929330e+02,  5.68837993e+02],
       [ 2.52891668e+02,  1.08352520e+03],
       [ 1.62734174e+02,  6.97892999e+02],
       [ 5.21072302e-01,  3.47843825e-01],
       [ 1.43908691e+02,  6.14907332e+02],
       [ 2.34609451e+02,  1.00493680e+03]])

In [ ]:
from sklearn.metrics import r2_score
Accuracy=r2_score(Y_test,y_pred)*100
print(" Accuracy of the model is %.2f" %Accuracy)

 Accuracy of the model is 87.16


In [ ]:
input_data=(3,1,6600,657)
# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardize the input data
#std_data = scaler.transform(input_data_reshaped)
#print(std_data)

prediction = model.predict(input_data_reshaped)
print(prediction)



[[ 308.5821342  1320.69039543]]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import pickle

In [ ]:
filename = 'dredger_calculator.sav'
pickle.dump(model, open(filename, 'wb'))

In [ ]:
loaded_model = pickle.load(open('dredger_calculator.sav', 'rb'))